name: 'Config Override Core Fields'
type: module
description: 'Provides hints to how form elements map to configuration objects.'
# core: 8.x
package: 'Administration'

# Information added by Drupal.org packaging script on 2018-02-26
version: '8.x-1.0-rc1'
core: '8.x'
project: 'config_override_core_fields'
datestamp: 1519641489
