enabled: windows_aad
settings:
  redirect_url: ''
  client_id: b7c79a3e-b92b-468b-b3b6-ab6956e5d444
  client_secret: wgaI0Cu0JVkOkZ/u9gS7QwdPs6g+PHg6fhBSlE+Cbs0=
  authorization_endpoint_wa: 'https://login.microsoftonline.com/237582ad-3eab-4d44-8688-06ca9f2e613b/oauth2/authorize'
  token_endpoint_wa: 'https://login.microsoftonline.com/237582ad-3eab-4d44-8688-06ca9f2e613b/oauth2/token'
  userinfo_endpoint_wa: 'https://login.microsoftonline.com/237582ad-3eab-4d44-8688-06ca9f2e613b/oauth2/UserInfo'
  userinfo_graph_api_wa: 0
  userinfo_graph_api_use_other_mails: 0
  userinfo_update_email: 0
  hide_email_address_warning: 0
dependencies:
  module:
    - openid_connect_windows_aad
  enforced:
    module:
      - openid_connect_windows_aad
